# Generated by Django 3.2.18 on 2024-02-04 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlarFolgas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idmilitar', models.IntegerField(blank=True, default=0, verbose_name='Id Militar')),
                ('idcirculo', models.IntegerField(blank=True, default=-1, verbose_name='Id Círculo')),
                ('idescala', models.IntegerField(verbose_name='Escala')),
                ('red', models.IntegerField(blank=True, default=100, null=True, verbose_name='Folga Vermelha')),
                ('black', models.IntegerField(blank=True, default=100, null=True, verbose_name='Folga Preta')),
                ('realred', models.IntegerField(default=100, verbose_name='Folga Vermelha')),
                ('realblack', models.IntegerField(default=100, verbose_name='Folga Preta')),
            ],
            options={
                'verbose_name': 'Folga',
                'verbose_name_plural': 'Folgas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DesignarEscala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idmilitar', models.IntegerField(blank=True, default=0, verbose_name='Id Militar')),
                ('idcirculo', models.IntegerField(blank=True, default=0, verbose_name='Id Círculo')),
                ('idescala', models.IntegerField(blank=True, default=0, verbose_name='Id Escala')),
                ('preta', models.BooleanField(blank=True, default=True, verbose_name='Preta')),
                ('vermelha', models.BooleanField(blank=True, default=True, verbose_name='Vermelha')),
                ('seg', models.BooleanField(blank=True, default=True, verbose_name='Seg')),
                ('ter', models.BooleanField(blank=True, default=True, verbose_name='Ter')),
                ('qua', models.BooleanField(blank=True, default=True, verbose_name='Qua')),
                ('qui', models.BooleanField(blank=True, default=True, verbose_name='Qui')),
                ('sex', models.BooleanField(blank=True, default=True, verbose_name='Sex')),
                ('sab', models.BooleanField(blank=True, default=True, verbose_name='Sáb')),
                ('dom', models.BooleanField(blank=True, default=True, verbose_name='Dom')),
            ],
            options={
                'verbose_name': 'Designar',
                'verbose_name_plural': 'Designados',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Dispensas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idmilitar', models.IntegerField(verbose_name='Id Militar')),
                ('idcirculo', models.IntegerField(verbose_name='Id Círculo')),
                ('datainicio', models.DateField(verbose_name='Início')),
                ('datafim', models.DateField(verbose_name='Fim')),
                ('motivo', models.CharField(max_length=100, verbose_name='Motivo')),
                ('prejuizo', models.BooleanField(blank=True, choices=[(1, 'SIM'), (0, 'NÃO')], default=True, verbose_name='Prejuízo da Escala?')),
            ],
            options={
                'verbose_name': 'Dispensa',
                'verbose_name_plural': 'Dispensas',
                'ordering': ['idmilitar'],
            },
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=40, verbose_name='Descrição')),
                ('ticado', models.BooleanField(blank=True, default=True, verbose_name='Marcado?')),
                ('precedencia', models.IntegerField(default=0, verbose_name='Precedência')),
                ('nrmilitaresnaescala', models.IntegerField(default=3, verbose_name='Nº Mil na Escala?')),
                ('idcirculo', models.IntegerField(choices=[(0, 'Oficial'), (1, 'ST/SGT'), (2, 'CB/SD'), (3, 'TODOS')], verbose_name='Círculo Hierárquico')),
                ('qtdporescala', models.IntegerField(default=1, verbose_name='Qtos escalados por dia?')),
                ('corrida', models.BooleanField(choices=[(1, 'SIM'), (0, 'NÃO')], default=0, verbose_name='Escala Corrida?')),
                ('folgaminima', models.IntegerField(default=1, verbose_name='Folga Mínima?')),
            ],
            options={
                'verbose_name': 'Escala',
                'verbose_name_plural': 'Escalas',
                'ordering': ['precedencia'],
            },
        ),
        migrations.CreateModel(
            name='Feriados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(max_length=10, verbose_name='Data')),
                ('descricao', models.CharField(max_length=60, verbose_name='Feriado')),
                ('dia', models.CharField(blank=True, max_length=15, verbose_name='Dia da Semana')),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'ordering': ['data'],
            },
        ),
    ]
