# Generated by Django 4.2.10 on 2024-03-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='corrida',
            field=models.BooleanField(choices=[(1, 'SIM'), (0, 'NÃO')], default=0, verbose_name='Corrida'),
        ),
        migrations.AlterField(
            model_name='escala',
            name='folgaminima',
            field=models.IntegerField(default=1, verbose_name='Folga Mínima'),
        ),
        migrations.AlterField(
            model_name='escala',
            name='qtdporescala',
            field=models.IntegerField(default=1, verbose_name='Qtde por dia'),
        ),
        migrations.AlterField(
            model_name='escala',
            name='ticado',
            field=models.BooleanField(blank=True, default=True, verbose_name='Marcado'),
        ),
    ]
