# Generated by Django 4.2.10 on 2024-03-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_user_posto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['posto'], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AddField(
            model_name='user',
            name='codom',
            field=models.IntegerField(blank=True, choices=[(6122, '40º BI'), (1503, '23º BC'), (1438, 'Ba Adm Gu F'), (62117, '10º CGCFEx'), (37820, '16ª Cia PE'), (15297, '52º CT'), (20404, 'CMF'), (24679, 'Cmdo 10ª RM'), (30619, 'Cia C 10ª RM'), (40709, '10º D Sup'), (59808, 'H Ge Fortaleza'), (65060, 'Pq R Mnt/10')], null=True, verbose_name='OM'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Ativo?'),
        ),
    ]
