# Generated by Django 4.2.10 on 2024-03-15 18:50

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_user_options_user_codom_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='confirmed',
            field=models.BooleanField(blank=True, default=False, verbose_name='Confirmado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(re.compile('[0-9]'), 'CPF só pode conter digitos de 0 a 9', 'invalid')], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='user',
            name='data_nasc',
            field=models.DateField(blank=True, null=True, verbose_name='Nascido em'),
        ),
        migrations.AlterField(
            model_name='user',
            name='data_praca',
            field=models.DateField(blank=True, null=True, verbose_name='Praça de'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(blank=True, choices=[(1, 'Administrador'), (0, 'Comum')], default=0, verbose_name='Perfil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='posto',
            field=models.IntegerField(blank=True, choices=[(5, 'Cel'), (6, 'T Cel'), (7, 'Maj'), (8, 'Cap'), (9, '1º Ten'), (10, '2º Ten'), (11, 'Asp'), (12, 'S Ten'), (13, '1º Sgt'), (14, '2º Sgt'), (15, '3º Sgt'), (16, 'Cb'), (17, 'SD')], null=True, verbose_name='Posto/Grad'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel1',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-]+$'), 'O nome de usuário só pode conter letras, digitos ou os seguintes caracteres: @/./+/-/_', 'invalid')], verbose_name='Usuário'),
        ),
    ]
