# Generated by Django 4.2.10 on 2024-03-12 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0003_militar_codom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militar',
            name='idcirculo',
            field=models.IntegerField(blank=True, choices=[(0, 'Oficial'), (1, 'ST/SGT'), (2, 'CB/SD'), (3, 'TODOS')], verbose_name='Círculo'),
        ),
    ]
